name: sign_language
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localization: ^0.2.0
  image_picker: ^1.1.1
  dio: ^5.4.1
  carousel_slider: ^5.0.0
  permission_handler: ^11.3.1
  flutter_tts: ^3.8.5
  shared_preferences: ^2.2.2
  flutter_screenutil: ^5.7.0
  provider: ^6.1.1
  google_fonts: ^6.1.0
  lottie: ^3.1.2
  flutter_sound_record: ^3.3.2
  just_audio: ^0.9.38
  animated_text_kit: ^4.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/back/
    - assets/images/english_letters/
    - assets/lang/
    - assets/animations/

